services:
  app:
    build:
      context: .
      dockerfile: docker/dev/dockerfile.app.dev
    container_name: payhero_admin
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - payhero_network
    depends_on:
      - mysql
      - redis
    environment:
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_KEY=$APP_KEY
      - APP_DEBUG=$APP_DEBUG
      - APP_URL=$APP_URL
      - LOG_CHANNEL=$LOG_CHANNEL
      - LOG_DEPRECATIONS_CHANNEL=$LOG_DEPRECATIONS_CHANNEL
      - LOG_LEVEL=$LOG_LEVEL
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
      - REDIS_SESSION_HOST=$REDIS_SESSION_HOST
      - REDIS_SESSION_PASSWORD=$REDIS_SESSION_PASSWORD
      - REDIS_SESSION_PORT=$REDIS_SESSION_PORT
      - REDIS_SESSION_DB=$REDIS_SESSION_DB
      - REDIS_HORIZON_HOST=$REDIS_HORIZON_HOST
      - REDIS_HORIZON_PASSWORD=$REDIS_HORIZON_PASSWORD
      - REDIS_HORIZON_PORT=$REDIS_HORIZON_PORT
      - REDIS_HORIZON_DB=$REDIS_HORIZON_DB
      - REDIS_STATEMENT_HOST=$REDIS_STATEMENT_HOST
      - REDIS_STATEMENT_PASSWORD=$REDIS_STATEMENT_PASSWORD
      - REDIS_STATEMENT_PORT=$REDIS_STATEMENT_PORT
      - REDIS_STATEMENT_DB=$REDIS_STATEMENT_DB
      - REDIS_CACHE_HOST=$REDIS_CACHE_HOST
      - REDIS_CACHE_PASSWORD=$REDIS_CACHE_PASSWORD
      - REDIS_CACHE_PORT=$REDIS_CACHE_PORT
      - REDIS_CACHE_DB=$REDIS_CACHE_DB
      - QUEUE_CONNECTION=$QUEUE_CONNECTION
      - QUEUE_FAILED_DRIVER=$QUEUE_FAILED_DRIVER
      - CACHE_DRIVER=$CACHE_DRIVER
      - SESSION_DRIVER=$SESSION_DRIVER
      - SESSION_LIFETIME=$SESSION_LIFETIME
      - COMPOSER_PROCESS_TIMEOUT=$COMPOSER_PROCESS_TIMEOUT
      - PHP_MEMORY_LIMIT=$PHP_MEMORY_LIMIT
      - XDEBUG_MODE=$XDEBUG_MODE
      - HEALTH_CHECK_TIMEOUT=$HEALTH_CHECK_TIMEOUT
      - HEALTH_CHECK_RETRIES=$HEALTH_CHECK_RETRIES
      - MAIL_MAILER=$MAIL_MAILER
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME=$MAIL_FROM_NAME

  webserver:
    build:
      context: .
      dockerfile: docker/dev/dockerfile.nginx
    container_name: payhero_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./storage/logs/nginx:/var/log/nginx
      - ./docker/dev/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    environment:
      APP_NAME: PayHero
      APP_ENV: local
    networks:
      - payhero_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: payhero_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/dev/config/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - payhero_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootsecret}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:alpine
    container_name: payhero_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - payhero_network
    environment:
      - APP_NAME=$APP_NAME
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
      - REDIS_SESSION_HOST=$REDIS_SESSION_HOST
      - REDIS_SESSION_PASSWORD=$REDIS_SESSION_PASSWORD
      - REDIS_SESSION_PORT=$REDIS_SESSION_PORT
      - REDIS_SESSION_DB=$REDIS_SESSION_DB
      - REDIS_HORIZON_HOST=$REDIS_HORIZON_HOST
      - REDIS_HORIZON_PASSWORD=$REDIS_HORIZON_PASSWORD
      - REDIS_HORIZON_PORT=$REDIS_HORIZON_PORT
      - REDIS_HORIZON_DB=$REDIS_HORIZON_DB
      - REDIS_STATEMENT_HOST=$REDIS_STATEMENT_HOST
      - REDIS_STATEMENT_PASSWORD=$REDIS_STATEMENT_PASSWORD
      - REDIS_STATEMENT_PORT=$REDIS_STATEMENT_PORT
      - REDIS_STATEMENT_DB=$REDIS_STATEMENT_DB
      - REDIS_CACHE_HOST=$REDIS_CACHE_HOST
      - REDIS_CACHE_PASSWORD=$REDIS_CACHE_PASSWORD
      - REDIS_CACHE_PORT=$REDIS_CACHE_PORT
      - REDIS_CACHE_DB=$REDIS_CACHE_DB
      - CACHE_DRIVER=$CACHE_DRIVER
      - SESSION_DRIVER=$SESSION_DRIVER
      - SESSION_LIFETIME=$SESSION_LIFETIME

networks:
  payhero_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: