<?php

namespace Modules\Core\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Laracasts\Presenter\PresentableTrait;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Core\Presenters\TransactionPresenter;
use App\Traits\LogsActivity;
use Exception;

/**
 * @property integer $id
 * @property integer $sale_id
 * @property integer $gateway_id
 * @property integer $company_id
 * @property string $value
 * @property integer $type
 * @property string $status
 * @property string $release_date
 * @property string $created_at
 * @property string $updated_at
 * @property string $percentage_rate
 * @property string $transaction_rate
 * @property string $gateway_released_at
 * @property boolean $is_waiting_withdrawal
 * @property integer $withdrawal_id
 * @property Company $company
 * @property Sale $sale
 * @property Gateway $gateway
 * @property Withdrawal $withdrawal
 * @property Collection $antecipatedTransactions
 * @property Collection $transfers
 * @method TransactionPresenter present()
 */
class Transaction extends Model
{
    use LogsActivity;
    use PresentableTrait;
    use SoftDeletes;

    protected $presenter = TransactionPresenter::class;

    protected $keyType = 'integer';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'sale_id',
        'gateway_id',
        'company_id',
        'invitation_id',
        'value',
        'type',
        'status',
        'status_enum',
        'release_date',
        'percentage_rate',
        'transaction_rate',
        'installment_tax',
        'created_at',
        'updated_at',
        'gateway_released_at',
        'is_waiting_withdrawal',
        'withdrawal_id',
        'gateway_transferred'
    ];

    protected static $logFillable = true;

    protected static $logUnguarded = true;

    protected static $logOnlyDirty = true;

    protected static $submitEmptyLogs = false;

    public function save(array $options = [])
    {
        $transaction = parent::save($options);
        if ($this->value < 0) {
            report(new Exception("Created Transaction valor negativo: {$this->id} "));
        }

        return $transaction; // TODO: Change the autogenerated stub
    }

    public function update(array $attributes = [], array $options = [])
    {
        $transaction = parent::update($attributes, $options);
        if ($this->value < 0) {
            report(new Exception("Update Transaction valor negativo: {$this->id}"));
        }

        return $transaction; // TODO: Change the autogenerated stub
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function sale()
    {
        return $this->belongsTo(Sale::class);
    }

    public function anticipatedTransactions()
    {
        return $this->hasMany(AnticipatedTransaction::class);
    }

    public function transfers()
    {
        return $this->hasMany(Transfer::class);
    }

    public function invitation()
    {
        return $this->belongsTo(Invitation::class);
    }

    public function productPlanSales()
    {
        return $this->hasMany(ProductPlanSale::class, 'sale_id', 'sale_id');
    }

    public function gateway() {
        return $this->belongsTo(Gateway::class);
    }

    public function withdrawal() {
        return $this->belongsTo(Withdrawal::class);
    }

    public function blockReasonSale()
    {
        return $this->hasMany(BlockReasonSale::class, 'sale_id', 'sale_id');
    }
}
