name: App Admin Full Deploy and Restart

run-name: Full Deploy and Restart to Production by ${{ github.actor }}

on:
    schedule:
      # Agendar o workflow para rodar sempre aos 10 minutos de cada hora
      - cron: "10 * * * *"
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_DEFAULT_REGION }}

            - name: Execute git reset
              run: |
                  aws ssm send-command \
                    --document-name "AWS-RunShellScript" \
                    --targets Key=tag:Name,Values=admin-azc-prd \
                    --parameters '{
                      "commands": [
                        "cd /var/www/html/admin.azcend.com.br",
                        "systemctl stop nginx php8.2-fpm",
                        "sudo -H -u ubuntu bash -c '"'"'git --git-dir=/var/www/html/admin.azcend.com.br/.git --work-tree=/var/www/html/admin.azcend.com.br reset --hard'"'"'",
                        "sudo -H -u ubuntu bash -c '"'"'git --git-dir=/var/www/html/admin.azcend.com.br/.git --work-tree=/var/www/html/admin.azcend.com.br pull'"'"'"
                      ],
                      "workingDirectory": ["/var/www/html/admin.azcend.com.br"],
                      "executionTimeout": ["3600"]
                    }' \
                    --timeout-seconds 600 \
                    --max-concurrency "50" \
                    --max-errors "0" \
                    --comment "Git reset before deploy"

            - name: Deploy to EC2
              run: |
                  aws ssm send-command \
                    --document-name "AWS-RunShellScript" \
                    --targets Key=tag:Name,Values=admin-azc-prd \
                    --parameters '{
                      "commands": [
                        "sudo chmod +x /var/www/html/admin.azcend.com.br/deploy.sh && sudo /var/www/html/admin.azcend.com.br/deploy.sh"
                      ],
                      "workingDirectory": ["/var/www/html/admin.azcend.com.br"],
                      "executionTimeout": ["3600"]
                    }' \
                    --timeout-seconds 600 \
                    --max-concurrency "50" \
                    --max-errors "0" \
                    --comment "Production Deploy - App Admin"
