# This workflow deploys to production by pushing changes to the main branch or manually.
# It's a very simple script that makes an API call on AWS Systems Manager via CLI and invokes the execution of a script document (passing the commands) that will be executed by SSM.

name: App Admin

run-name: Workflow initiated by ${{ github.actor }}

on:
    # Triggers the workflow on push for the main branch
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "us-east-1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy to EC2
              run: |
                  aws ssm send-command \
                  --document-name "AWS-RunShellScript" \
                  --document-version "1" \
                  --targets Key=tag:Name,Values=admin-azc-prd \
                  --parameters '
                        {
                            "commands": [
                                "service nginx stop",
                                "sudo -H -u ubuntu bash -c '"'"'git --git-dir=/var/www/html/admin.azcend.com.br/.git --work-tree=/var/www/html/admin.azcend.com.br reset --hard origin/main'"'"'",
                                "sudo -H -u ubuntu bash -c '"'"'git --git-dir=/var/www/html/admin.azcend.com.br/.git --work-tree=/var/www/html/admin.azcend.com.br pull'"'"'",
                                "rm -rf /var/www/html/admin.azcend.com.br/storage",
                                "ln -s /var/www/html/efs-admin-azc-prd/storage /var/www/html/admin.azcend.com.br/storage",
                                "service nginx start",
                                "supervisorctl restart all",
                                "sudo -H -u ubuntu bash -c '"'"'php /var/www/html/admin.azcend.com.br/artisan horizon:publish'"'"'",
                                "php /var/www/html/admin.azcend.com.br/artisan cache:clear",
                                "php /var/www/html/admin.azcend.com.br/artisan config:clear",
                                "php /var/www/html/admin.azcend.com.br/artisan route:clear",
                                "php /var/www/html/admin.azcend.com.br/artisan view:clear",
                                "chown -R ubuntu:www-data /var/www/html/admin.azcend.com.br/storage /var/www/html/admin.azcend.com.br/bootstrap/cache",
                                "chmod -R 775 /var/www/html/admin.azcend.com.br/storage /var/www/html/admin.azcend.com.br/bootstrap/cache",
                                "setfacl -R -m u:ubuntu:rwx /var/www/html/admin.azcend.com.br",
                                "setfacl -R -m g:www-data:rwx /var/www/html/admin.azcend.com.br",
                                "setfacl -dR -m u:ubuntu:rwx /var/www/html/admin.azcend.com.br",
                                "setfacl -dR -m g:www-data:rwx /var/www/html/admin.azcend.com.br",
                                "sudo -H -u ubuntu bash -c '"'"'php /var/www/html/admin.azcend.com.br/artisan migrate --force'"'"'",
                            ],
                            "workingDirectory": ["/var/www/html/admin.azcend.com.br"],
                            "executionTimeout": ["3600"]
                        }
                        ' \
                  --timeout-seconds 600 \
                  --max-concurrency "50" \
                  --comment "Deploy App Admin" \
                  --max-errors "0"
